version: '3.8'

services:
  web:
    build: .
    command: python main.py run -h 0.0.0.0
    ports:
      - 5001:5000
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis: 
    image: redislabs/redismod
    ports:
      - '6379:6379' 
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
    - '8001:8001'

volumes:
  postgres_data: